CREATE TABLE genres (
  id SERIAL PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE items (
  id SERIAL PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  published_date DATE NOT NULL,
  archived BOOLEAN NOT NULL,
  genre_id INT,
  FOREIGN KEY (genre_id) REFERENCES genres(id)
);

CREATE TABLE music_albums (
  id SERIAL PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
  on_spotify BOOLEAN NOT NULL,
  FOREIGN KEY (item_id) REFERENCES items(id)
);
